### ISSUE TITLE
Idea2023.3不兼容

### ISSUE THREAD

**Issue by dovecheng** [mdddj/dd_flutter_idea_plugin#35]
![image](https://github.com/mdddj/dd_flutter_idea_plugin/assets/34654145/22d384c1-c747-4967-8296-90ca965802e2)

**Comment by mdddj** [comment]
[FlutterX-3.9.2.IU.zip](https://github.com/mdddj/dd_flutter_idea_plugin/files/13632459/FlutterX-3.9.2.IU.zip)
下载后从本地安装，新版本已经提交到 JB 市场，等他们上班审核即可搜索下载

**Comment by mdddj** [comment]
可以在搜索下载了
