### ISSUE TITLE
不能很好的检测出 lib的dev版本

### ISSUE THREAD

**Issue by zhoujia456888** [mdddj/dd_flutter_idea_plugin#37]
有些lib是dev版本的，版本号其实更高一些，但是还是会提示新版本。
![image](https://github.com/mdddj/dd_flutter_idea_plugin/assets/7905253/e149006f-8fbd-48b4-813d-6870bc7c9cbf)

**Comment by mdddj** [comment]
升级到4.0.1版本试试

**Comment by zhoujia456888** [comment]
4.0.1版本一开IDEA就会报错

**Comment by mdddj** [comment]
升级到4.0.3版本试试

**Comment by zhoujia456888** [comment]
好像可以了，暂时没问题
